import type { NextPage } from 'next'
import Head from 'next/head'
import WalletConnect from '../components/WalletConnect'
import { useStoreActions, useStoreState } from "../utils/store"
import Link from 'next/link'
import { useState, useEffect} from 'react'
import { getAssets } from "../utils/cardano";
import NftGrid from "../components/NftGrid";
import initLucid from '../utils/lucid'

import { useRouter } from 'next/router';

const Home: NextPage = () => {
  const walletStore = useStoreState((state: any) => state.wallet)
  const [nftList, setNftList] = useState([])
  const [jsonData, setJsonData] = useState<any>(null);
  const [secretData, setSecretData] = useState<any>(null);
  // for Redirect to offChain.tsx
  const router = useRouter();

  useEffect(() => {
    // Call fetchSecretData when the component mounts or walletStore.address changes
    fetchSecretData();
    //const lucid = initLucid(walletStore.name)
    if (walletStore.address != "") {
      getAssets(walletStore.address)
        .then((res: any) => { setNftList(res.addressInfo.nfts) })
    }

    // for Redirect to offChain.tsx
    router.push('/offChainV2');
  }, [walletStore.address])


  const fetchData = async () => {
    try {
      const response = await fetch('/secret.json'); // This will automatically fetch from the public folder
      const data = await response.json();
      setJsonData(data);
    } catch (error) {
      console.error('Error fetching data:', error);
    }
  };  

  const fetchSecretData = async () => {
    try {
      const response = await fetch('/api/getData');
      const data = await response.json();
      setSecretData(data);
    } catch (error) {
      console.error('Error fetching secret data:', error);
    }
  };  

  return null;
//   return (
//     <div className="px-10">
//       <Head>
//         <title>Cardano dapp quickstart</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="navbar bg-base-100">
//         <div className="flex-1">
//           <Link href="/" className="btn btn-ghost normal-case text-xl">Cardano</Link>
//         </div>
//         <div className="flex-none">
//           <WalletConnect />
//         </div>
//       </div>
//       <div>Address: {walletStore.address}</div>
//       <div>Your NFTs:</div>
//       <NftGrid nfts={nftList} />      
//       <div className="mx-40 my-10">
//         <Link href="offChain">
//           <button className="btn btn-primary m-5" >Decentralized Seed Phrase Manager</button>
//         </Link>
//         {/* <div>Your NFTs:</div>
//         <NftGrid nfts={nftList} /> */}
//       </div>
//       <div>
//         {/* <button className="btn btn-secondary m-5" onClick={fetchData}>Fetch Data</button> */}
//         {/* <button className="btn btn-secondary m-5" onClick={() => { testCode() }}> testCode</button> */}
//         {jsonData && (
//           <div>
//             {/* <pre>{JSON.stringify(jsonData, null, 2)}</pre>   // this gives the whole JSON file */}  
//             <h2>Item 1 Description: {jsonData.items[0].description}</h2>
//           </div>
//         )}
//       </div>
//       {/* <div> */}
//         {/* <button className="btn btn-secondary m-5" onClick={fetchSecretData}>Fetch Secret Data</button> */}
//         {/* <button className="btn btn-secondary m-5" onClick={() => { testCode() }}> testCode</button> */}
//         {/* {secretData && ( */}
//           {/* <div> */}
//             {/* <pre>{JSON.stringify(secretData, null, 2)}</pre>   // this gives the whole JSON file   */}
//             {/* <h2> {secretData.seed[0].name} : {secretData.seed[0].description}</h2> */}
//           {/* </div> */}
//         {/* )} */}
//       {/* </div>  */}
//   </div>          
//   )
 }

export default Home
